import { z } from 'zod'

export const comboTimeOfDaySchema = z.enum(['morning', 'afternoon', 'evening', 'night'])
export const comboWeatherModeSchema = z.enum(['any', 'hot', 'cold', 'rainy'])

export const categoryPairRuleSchema = z.object({
  id: z.string().min(1).max(60),
  enabled: z.boolean().default(true),
  priority: z.number().int().min(0).max(100).default(50),
  fromCategoryId: z.string().min(1).max(60),
  toCategoryIds: z.array(z.string().min(1).max(60)).min(1).max(12),
  label: z.string().min(1).max(120),
  tagHints: z.array(z.string().min(1).max(40)).default([]),
})

export const comboTemplateSchema = z.object({
  id: z.string().min(1).max(60),
  enabled: z.boolean().default(true),
  priority: z.number().int().min(0).max(100).default(50),
  title: z.string().min(1).max(80),
  reason: z.string().min(1).max(200),
  itemCount: z.number().int().min(2).max(5).default(3),
  moods: z.array(z.string().min(1).max(40)).default([]),
  timeOfDay: z.array(comboTimeOfDaySchema).default([]),
  weather: comboWeatherModeSchema.default('any'),
  requireDistinctCategories: z.boolean().default(true),
  categoryFilter: z.array(z.string().min(1).max(60)).default([]),
})

export const comboRecommendationSettingsSchema = z.object({
  pairingEnabled: z.boolean().default(true),
  pairingSectionTitle: z.string().max(60).default('پیشنهاد ترکیب'),
  comboItemCount: z.number().int().min(2).max(5).default(3),
  minComboItems: z.number().int().min(2).max(5).default(2),
  requireDistinctCategories: z.boolean().default(true),
  preferComplementaryTags: z.boolean().default(true),
  templatesFirst: z.boolean().default(true),
  categoryPairs: z.array(categoryPairRuleSchema).max(40).default([]),
  templates: z.array(comboTemplateSchema).max(20).default([]),
  fallbackPairingReason: z.string().max(120).default('کنار این آیتم عالی می‌شود'),
  fallbackComboReason: z.string().max(200).default('انتخاب متنوع بر اساس ساعت و حال شما'),
})

export type CategoryPairRule = z.infer<typeof categoryPairRuleSchema>
export type ComboTemplate = z.infer<typeof comboTemplateSchema>
export type ComboRecommendationSettings = z.infer<typeof comboRecommendationSettingsSchema>

export const DEFAULT_COMBO_RECOMMENDATIONS: ComboRecommendationSettings = {
  pairingEnabled: true,
  pairingSectionTitle: 'پیشنهاد ترکیب',
  comboItemCount: 3,
  minComboItems: 2,
  requireDistinctCategories: true,
  preferComplementaryTags: true,
  templatesFirst: true,
  fallbackPairingReason: 'کنار این آیتم عالی می‌شود',
  fallbackComboReason: 'انتخاب متنوع بر اساس ساعت، آب‌وهوا و حال شما',
  categoryPairs: [
    {
      id: 'hot-drink-dessert',
      enabled: true,
      priority: 90,
      fromCategoryId: 'arabica',
      toCategoryIds: ['cake', 'waffle', 'breakfast'],
      label: 'کنار قهوه، دسر یا صبحانه عالیه',
      tagHints: ['sweet', 'cozy'],
    },
    {
      id: 'espresso-dessert',
      enabled: true,
      priority: 88,
      fromCategoryId: 'coffee5050',
      toCategoryIds: ['cake', 'waffle'],
      label: 'یک چیز شیرین کنارش بچسبه',
      tagHints: ['sweet'],
    },
    {
      id: 'hotcup-pastry',
      enabled: true,
      priority: 86,
      fromCategoryId: 'hotcup',
      toCategoryIds: ['cake', 'waffle', 'breakfast'],
      label: 'پیشنهاد: مزه‌ی شیرین کنارش',
      tagHints: ['sweet', 'cozy'],
    },
    {
      id: 'cold-drink-snack',
      enabled: true,
      priority: 85,
      fromCategoryId: 'icedcoffee',
      toCategoryIds: ['cake', 'waffle', 'salad'],
      label: 'یک میان‌وعده سبک کنارش خوبه',
      tagHints: ['light', 'fresh'],
    },
    {
      id: 'shake-dessert',
      enabled: true,
      priority: 84,
      fromCategoryId: 'shake',
      toCategoryIds: ['waffle', 'cake'],
      label: 'شیرینی کنارش کاملش می‌کنه',
      tagHints: ['sweet'],
    },
    {
      id: 'food-drink',
      enabled: true,
      priority: 82,
      fromCategoryId: 'breakfast',
      toCategoryIds: ['arabica', 'herbal', 'fresh'],
      label: 'نوشیدنی گرم یا خنک کنارش پیشنهاد می‌شود',
      tagHints: ['hot', 'fresh'],
    },
    {
      id: 'waffle-drink',
      enabled: true,
      priority: 80,
      fromCategoryId: 'waffle',
      toCategoryIds: ['arabica', 'milkmix', 'fresh'],
      label: 'نوشیدنی کنار وافل عالیه',
      tagHints: ['hot', 'cold'],
    },
    {
      id: 'cake-drink',
      enabled: true,
      priority: 78,
      fromCategoryId: 'cake',
      toCategoryIds: ['arabica', 'herbal', 'milkmix'],
      label: 'نوشیدنی کنار کیک پیشنهاد می‌شود',
      tagHints: ['hot', 'relax'],
    },
    {
      id: 'salad-drink',
      enabled: true,
      priority: 76,
      fromCategoryId: 'salad',
      toCategoryIds: ['fresh', 'herbal', 'icedcoffee'],
      label: 'نوشیدنی خنک کنار سالاد مناسب است',
      tagHints: ['fresh', 'cold'],
    },
    {
      id: 'icecream-hot-drink',
      enabled: true,
      priority: 70,
      fromCategoryId: 'icecream',
      toCategoryIds: ['arabica', 'herbal', 'hotcup'],
      label: 'نوشیدنی گرم کنار بستنی جذابه',
      tagHints: ['hot', 'cozy'],
    },
  ],
  templates: [
    {
      id: 'morning-start',
      enabled: true,
      priority: 90,
      title: 'صبحانه کامل',
      reason: 'شروع روز با انرژی و تازگی',
      itemCount: 3,
      timeOfDay: ['morning'],
      weather: 'any',
      moods: [],
      requireDistinctCategories: true,
      categoryFilter: ['breakfast', 'arabica', 'fresh'],
    },
    {
      id: 'hot-weather',
      enabled: true,
      priority: 88,
      title: 'پکیج خنک',
      reason: 'فرار از گرما با نوشیدنی و دسر سرد',
      itemCount: 3,
      timeOfDay: [],
      weather: 'hot',
      moods: [],
      requireDistinctCategories: true,
      categoryFilter: ['icedcoffee', 'shake', 'fresh', 'icecream'],
    },
    {
      id: 'cold-weather',
      enabled: true,
      priority: 86,
      title: 'ست گرم دل‌چسب',
      reason: 'گرما و آرامش برای هوای سرد',
      itemCount: 3,
      timeOfDay: [],
      weather: 'cold',
      moods: [],
      requireDistinctCategories: true,
      categoryFilter: ['arabica', 'hotcup', 'herbal', 'cake', 'waffle'],
    },
    {
      id: 'evening-relax',
      enabled: true,
      priority: 84,
      title: 'عصرانه آرام',
      reason: 'طعم‌های گرم و دل‌چسب برای عصر',
      itemCount: 3,
      timeOfDay: ['evening', 'night'],
      weather: 'any',
      moods: [],
      requireDistinctCategories: true,
      categoryFilter: ['arabica', 'herbal', 'cake', 'waffle'],
    },
    {
      id: 'sweet-mood',
      enabled: true,
      priority: 82,
      title: 'کمبو شیرین‌کار',
      reason: 'لذت شیرینی بدون محدودیت',
      itemCount: 3,
      timeOfDay: [],
      weather: 'any',
      moods: ['sweet'],
      requireDistinctCategories: true,
      categoryFilter: ['cake', 'waffle', 'shake', 'icecream', 'milkmix'],
    },
    {
      id: 'fresh-mood',
      enabled: true,
      priority: 80,
      title: 'پکیج سبک و تازه',
      reason: 'سبک، تازه و رفرش',
      itemCount: 3,
      timeOfDay: [],
      weather: 'any',
      moods: ['fresh'],
      requireDistinctCategories: true,
      categoryFilter: ['fresh', 'salad', 'herbal', 'icedcoffee'],
    },
    {
      id: 'energetic-mood',
      enabled: true,
      priority: 78,
      title: 'کافه‌ورک فوکوس',
      reason: 'انرژی و تمرکز برای کار',
      itemCount: 3,
      timeOfDay: [],
      weather: 'any',
      moods: ['energetic'],
      requireDistinctCategories: true,
      categoryFilter: ['arabica', 'coffee5050', 'breakfast'],
    },
  ],
}
