import type { PosSettings } from './posTypes'

export const DEFAULT_POS_SETTINGS: PosSettings = {
  enabled: true,
  requireShiftOpen: true,
  receiptWidthMm: 80,
  receiptTemplateId: 'bold',
  receiptHighContrast: true,
  receiptHeaderText: '',
  receiptFooterText: 'از خرید شما سپاسگزاریم 🍦',
  showLogoOnReceipt: true,
  showQrOnReceipt: true,
  showShiftOnReceipt: true,
  autoPrintOnSale: true,
  autoPrintOnOnlineSettle: true,
  defaultPaymentMethod: 'CASH',
  allowMixedPayment: true,
  allowManualDiscount: true,
  maxDiscountPercentStaff: 10,
  maxDiscountPercentManager: 50,
  allowRefunds: true,
  requireRefundReason: true,
  requireManagerForRefund: false,
  soundOnAddItem: true,
  addItemSoundVolume: 0.45,
  shiftRoles: ['SUPER_ADMIN', 'MANAGER', 'STAFF'],
  discountRoles: ['SUPER_ADMIN', 'MANAGER', 'STAFF'],
}
