import type { MoodDefinition, StoreCopy, StoreLocation } from './types'

export const DEFAULT_LOCATION: StoreLocation = {
  lat: 32.5556,
  lon: 51.6722,
  label: 'اصفهان سیتی‌سنتر',
}

export const DEFAULT_MOODS: MoodDefinition[] = [
  {
    id: 'energetic',
    label: 'پرانرژی',
    emoji: '⚡',
    color: '#F26522',
    aiPrompt: 'حالم پرانرژیه، چی پیشنهاد می‌دی؟',
    tagWeights: { energy: 1, morning: 0.5 },
  },
  {
    id: 'relaxed',
    label: 'آرام',
    emoji: '🌿',
    color: '#4a8a60',
    aiPrompt: 'می‌خوام آروم باشم، چی مناسبه؟',
    tagWeights: { relax: 1, evening: 0.5, herbal: 0.8 },
  },
  {
    id: 'sweet',
    label: 'شیرین‌کار',
    emoji: '🍫',
    color: '#FF2D7B',
    aiPrompt: 'دور شیرینی‌ام، چی داری؟',
    tagWeights: { sweet: 1, dessert: 0.8 },
  },
  {
    id: 'fresh',
    label: 'تازه',
    emoji: '🍃',
    color: '#e85d8a',
    aiPrompt: 'چیز تازه و خنک می‌خوام',
    tagWeights: { fresh: 1, cold: 0.6 },
  },
  {
    id: 'cozy',
    label: 'دنج',
    emoji: '🔥',
    color: '#D94E10',
    aiPrompt: 'یه چیز گرم و دنج',
    tagWeights: { hot: 0.8, evening: 0.6, sweet: 0.4 },
  },
  {
    id: 'adventurous',
    label: 'ماجراجو',
    emoji: '🎲',
    color: '#E8A87C',
    aiPrompt: 'یه چیز جدید و متفاوت',
    tagWeights: { fresh: 0.5, energy: 0.3 },
  },
]

export const DEFAULT_STORE_COPY: StoreCopy = {
  appTagline: 'منوی هوشمند',
  installBanner: 'نصب اپ {storeName}',
  installButton: 'نصب',
  menuTitle: 'منوی {storeName}',
  storyEyebrow: 'ویترین',
  storyTitle: 'ویترین {storeName}',
  storyDescription: 'لحظه‌ای با محبوب‌ترین‌ها',
  storyBadge: 'ویژه',
  comboEyebrow: 'کمبو',
  comboTitle: 'کمبو هوشمند',
  comboDescription: '{storeName} خودش برایتان کمبو می‌سازد',
  comboOrderToast: 'کمبو هوشمند ثبت شد!',
  spinWheelHint: 'بچرخون — {storeName} برات یه انتخاب خوب پیدا می‌کنه',
  kioskTapStart: 'لمس کنید تا شروع شود',
  kioskTapOrder: 'برای سفارش لمس کنید',
  closedTitle: 'فعلاً بسته‌ایم',
  closedMessage: 'در حال حاضر سفارش‌گیری غیرفعال است.',
  closedHint: 'ساعات کاری: {openingHours}',
  currencySuffix: ' تومان',
  searchPlaceholder: 'جستجو در منو…',
  addToCartToast: '{name} به سبد اضافه شد',
  navHome: 'خانه',
  navIceCream: 'بستنی',
  navMenu: 'منو',
  navDiscover: 'کشف',
  navPlay: 'پیشنهاد',
  moodEyebrow: 'حال و هوا',
  moodTitle: 'حال و هوای شما',
  moodDescription: 'منو را بر اساس مودتان شخصی‌سازی کنید',
  smartPickReason: 'پیشنهاد ویژه {storeName}',
  smartComboTitle: 'کمبو هوشمند {storeName}',
  smsDisabledMessage: 'ثبت‌نام با پیامک هنوز فعال نشده. از پنل ادمین SMS.ir را تنظیم کنید.',
  smsRegisterNote: 'برای امنیت، ثبت‌نام و ورود فقط با کد یک‌بارمصرف (OTP) از طریق SMS.ir انجام می‌شود.',
  iceStep1Label: 'پایه',
  iceStep1Title: 'طعم پایه را انتخاب کنید',
  iceStep2Label: 'روکش',
  iceStep2Title: 'روکش شکلاتی را انتخاب کنید',
  iceStep3Label: 'فیلینگ',
  iceStep3Title: 'فیلینگ را انتخاب کنید',
  iceCustomName: 'بستنی سفارشی',
  scratchTitle: 'کارت شانس',
  scratchSubtitle: 'بخراش و جایزه بگیر!',
  scratchCanvasHint: 'بخراش و ببین!',
  scratchRewardCheckoutLabel: 'جایزه کارت شانس (با ثبت سفارش اضافه می‌شود)',
  scratchRewardSuccess: 'جایزه ثبت شد — در مرحله تکمیل سفارش نمایش داده می‌شود',
  navWaitLounge: 'سالن انتظار',
  waitLoungeTitle: 'سالن انتظار چیل',
  waitLoungeSubtitle: 'تا آماده شدن سفارش بازی کن و امتیاز جمع کن!',
  waitLoungeEnter: 'ورود به سالن انتظار',
  waitLoungePlayTeaser: 'بازی کن و امتیاز جمع کن',
  waitLoungePlayTitle: 'وقتشه بازی کنی!',
  waitLoungeReadyTitle: 'سفارشت آماده است!',
  waitLoungeReadyMessage: 'به سمت پیشخوان بیا و سفارشت رو تحویل بگیر',
  waitLoungePointsLabel: 'امتیاز چیل',
  waitLoungeRedeemLabel: 'استفاده از امتیاز',
  waitLoungeRedeemApplied: 'تخفیف امتیاز اعمال شد',
}
